// <auto-generated />
using System;
using LivrosApp.Infra.DATA.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LivrosApp.Infra.DATA.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20241106215813_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LivrosApp.DOMAIN.Entities.Livro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID");

                    b.Property<int>("AnoDePublicacao")
                        .HasColumnType("int")
                        .HasColumnName("ANODEPUBLICACAO");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit")
                        .HasColumnName("ATIVO");

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("AUTOR");

                    b.Property<DateTime?>("DataInclusao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATAINCLUSAO");

                    b.Property<DateTime?>("DataRetirada")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATARETIRADA");

                    b.Property<bool>("Disponibildade")
                        .HasColumnType("bit")
                        .HasColumnName("DISPONIBILIDADE");

                    b.Property<int>("Genero")
                        .HasColumnType("int")
                        .HasColumnName("GENERO");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TITULO");

                    b.HasKey("Id");

                    b.ToTable("LIVRO", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
